### ISSUE TITLE
'list' object has no attribute 'transpose'

### ISSUE THREAD

**Issue by fcs203** [taki0112/GAN_Metrics-Tensorflow#1]
I run the main.py but the Error message is 'list' object has no attribute 'transpose'
line 29, in frechet_inception_distance
    real_images = np.transpose(real_images, axes=[0, 3, 1, 2])
how can I fix it, thanks

**Comment by fcs203** [comment]
line '/real' should be './real'

**Comment by strommen-emil** [comment]
bro what was the solutiuon you cant just gatekeep it.
