### ISSUE TITLE
version

### ISSUE THREAD

**Issue by Ahalang** [taki0112/GAN_Metrics-Tensorflow#2]
Great work! when i run this code, i encounter some question. Can you tell me that the version of tensorflow、python?  What framework needs to be installed?  I run main.py , some error occurs,
No module named 'fid_kid'. What should I do? Thank you.

**Comment by taki0112** [comment]
TF : 1.13.1
Python : 3.6.8

And, fixed `main.py`
removed 'fid_kid', 
It's just folder name. sorry

**Comment by Ahalang** [comment]
Which images are represented by real_source and real_target respectively? i run your code of RelativisticGAN, it is a very goog job. How to test the picture of generating? Have you tried adding this metric directly to this code? Thank you very much.
